package mobile

import android.util.Log

/**
 * JNI bridge to libgojni.so — the Go olcRTC native library built by gomobile.
 * Package and class name MUST be "mobile.Mobile" to match the JNI exports
 * generated by gomobile bind from github.com/openlibrecommunity/olcrtc/mobile.
 */
object Mobile {

    private var loaded = false

    fun load(): Boolean {
        if (loaded) return true
        return try {
            System.loadLibrary("gojni")
            loaded = true
            _1init()
            setProviders()
            true
        } catch (e: UnsatisfiedLinkError) {
            Log.e("Mobile", "libgojni.so not found: ${e.message}")
            false
        }
    }

    // ---- lifecycle ----
    private external fun _1init()
    private external fun setProviders()

    external fun start(
        carrierName: String, roomID: String, clientID: String, keyHex: String,
        socksPort: Int, socksUser: String, socksPass: String
    ): String?

    external fun startWithTransport(
        carrierName: String, transportName: String, roomID: String, clientID: String,
        keyHex: String, socksPort: Int, socksUser: String, socksPass: String
    ): String?

    external fun stop()
    external fun isRunning(): Boolean
    external fun waitReady(): String?

    // ---- config ----
    external fun setTransport(transport: String)
    external fun setLink(link: String)
    external fun setDNS(dns: String)
    external fun setDebug(debug: Boolean)
    external fun setVP8Options(fps: Int, batchSize: Int)

    // ---- utilities ----
    external fun ping(
        carrierName: String, transportName: String, roomID: String, clientID: String,
        keyHex: String, socksPort: Int, timeoutMillis: Long, pingURL: String,
        vp8FPS: Long, vp8BatchSize: Long
    ): Long

    external fun check(
        carrierName: String, transportName: String, roomID: String, clientID: String,
        keyHex: String, socksPort: Int, timeoutMillis: Int, vp8FPS: Int, vp8BatchSize: Int
    ): Long

    // ---- protect / log ----
    external fun setProtector(protector: proxySocketProtector)
    external fun setLogWriter(writer: proxyLogWriter)
}

/**
 * JNI name must match Go's proxySocketProtector inner class.
 * Export: Java_mobile_Mobile_00024proxySocketProtector_protect
 */
class proxySocketProtector(private val impl: (Int) -> Boolean) {
    @Suppress("unused")
    fun protect(fd: Int): Boolean = impl(fd)
}

/**
 * JNI name must match Go's proxyLogWriter inner class.
 * Export: Java_mobile_Mobile_00024proxyLogWriter_writeLog
 */
class proxyLogWriter(private val impl: (String) -> Unit) {
    @Suppress("unused")
    fun writeLog(msg: String) { impl(msg) }
}
